apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: python-app
        image: mounikarangisetty/my-python-app:latest  # Replace with your Docker image
        ports:
        - containerPort: 80  # Port your application is running on

---apiVersion: v1kind: Servicemetadata:
  name: my-python-app-servicespec:
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 80  # Service port
    targetPort: 80  # Port where the app is running inside the container
  type: LoadBalancer  # Exposes the service externally (use NodePort if not using cloud provider)
