apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: python-app
        image: mounikarangisetty/my-python-app:latest  
        ports:
        - containerPort: 5000 

---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
spec:
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 5000 
  type: LoadBalancer
