version: '3.8'

services:
  app:
    image: mounikarangisetty/my-python-app:latest
    environment:
      - APP_ENV=production
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
