# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container to /my-python-app
WORKDIR /my-python-app

# Copy the current directory contents into the container at /my-python-app
COPY my-python-app/requirements.txt /my-python-app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY my-python-app/ /my-python-app/

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["python", "app.py"]
