services:
  app:
    image: mounikarangisetty/my-python-app:latest
    environment:
      - APP_ENV=production
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
