# Stage 1: Build stage
FROM python:3.8-slim AS builder

# Set the working directory
WORKDIR /my-python-app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application source code
COPY . .

# Stage 2: Final stage
FROM python:3.8-slim

WORKDIR /my-python-app

# Copy only the necessary files from the builder stage
COPY --from=builder /my-python-app /my-python-app

# Set environment variables
ENV APP_ENV=production

# Expose the port
EXPOSE 80

# Define a health check
HEALTHCHECK CMD curl --fail http://localhost:80 || exit 1

# Run the application
CMD ["python", "addition.py"]

