
groups:
- name: example_alerts
  rules:
  - alert: screpedurationalert
    expr: scrape_duration_seconds{job="my_python_app"} > 0.1
    for: 5s
    labels:
      severity: critical
    annotations:
      summary: "High request latency detected"
      description: "Request latency is above 0.5 seconds for more than 5 seconds."
 - alert: ServiceDown
    expr: up{job="my_python_app"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Service is down"
      description: "The service my_python_app is currently down."




