global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:
  - job_name: 'my_python_app'
    static_configs:
      - targets: ['localhost:5000']  # Adjust if your application runs on a different port

rule_files:
  - "alert_rules.yml"  # Reference to alert rules defined later
