global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']  # Address of your Alertmanager

rule_files:
  - 'alert_rules.yml'  # Your alert rules file

scrape_configs:
  - job_name: 'my_python_app'
    static_configs:
      - targets: ['13.127.16.150:8000']  # Your application metrics endpoint
