global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

rule_files:
  - 'alert_rules.yml'  # Your alert rules file

scrape_configs:
  - job_name: 'my_python_app'
    static_configs:
      - targets: ['3.110.32.132:8000'] 
